#!/bin/bash
# Sources tmux scripts from a predefined location
# This is a super super simple session/tmux window manager
#
# Example script:
#
# # 3 pane layout with vim open in the main pane
# new-window -n "example" -c "~/myproject" "vim foo"
# split-window
# split-window
# select-layout main-vertical

SCRIPTDIR="$HOME/.tmux/scripts"

if [[ -z $1 ]]; then
    echo "Usage: $0 PROFILENAME"
    echo "Loads a tmux profile from $SCRIPTDIR"
    echo
    echo "Available profiles:"
    ls "$SCRIPTDIR"
    exit 1
fi

FILENAME="$SCRIPTDIR/$1"

if [[ ! -e $FILENAME ]]; then
    echo "Profile $1 not found"
    exit 1
fi

tmux source "$FILENAME"
