#!/bin/bash
# NOTE: Don't use this, just use ssh -J GATEWAY_HOST instead
# SSH through a host
# For when you need something quick and dirty to use a gateway host and
# don't want to change your .ssh/config to do it automatically.
# Usage: ssh-via proxy.host.name real.host.name [commands]
echo "DEPRECATED: Don't use this - use ssh -J GATEWAY_HOST HOSTNAME instead"
ssh -J "$@"
