#!/bin/bash
# Adds a hook to the current git repository that will automatically add a DCO
# Signed-off-by message to every commit.
#
# Usage: git auto-signoff

set -euo pipefail

# Note: set -e will cause the script to exit if we're not in a git repository
REPO_ROOT=$(git rev-parse --show-toplevel)

HOOK_DIR="$REPO_ROOT/.git/hooks"
HOOK_FILE="$HOOK_DIR/prepare-commit-msg"

mkdir -p "$HOOK_DIR"

cat > "$HOOK_FILE" <<EOF
#!/bin/bash
# Automatically add Signed-off-by to commit messages
# From https://stackoverflow.com/questions/15015894

NAME=\$(git config user.name)
EMAIL=\$(git config user.email)

if [[ -z "\$NAME" ]]; then
    echo "empty git config user.name"
    exit 1
fi

if [[ -z "\$EMAIL" ]]; then
    echo "empty git config user.email"
    exit 1
fi

git interpret-trailers --if-exists doNothing --trailer \
    "Signed-off-by: \$NAME <\$EMAIL>" \
    --in-place "\$1"
EOF
chmod +x "$HOOK_FILE"
