#!/bin/bash
COLUMNS=$1
LINES=$2


if [[ -z $COLUMNS || -z $LINES ]]; then
    echo "Usage: $0 COLUMNS LINES"
    echo "Ouputs an escape sequence to resize the terminal window"
    exit 1
fi

if [[ $TERM =~ screen* ]]; then
    printf "\ePtmux;\e\e[8;%s;%st\e\\" "$LINES" "$COLUMNS"
else
    printf "\e[8;%s;%st" "$LINES" "$COLUMNS"
fi
